apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k4je2giz9-python
  janus-idp.io/tekton: k4je2giz9-python
  backstage.io/kubernetes-id: k4je2giz9-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k4je2giz9-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
